config/routes.rb
# -*- encoding : utf-8 -*-
Dumsnadno::Application.routes.draw do

  # Active Admin
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  
  mount Resque::Server.new, :at => "/resque"

  get "users/index"

  resources :homes
  resources :users do
    member do
      get :activate
    end
  end

  resources :user_sessions

  resources :password_resets

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resource :oauth do
    get :callback
  end
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider


  # LOGGED USER
  scope :constraints => lambda { |req| req.session.include?(:user_id) } do
    match 'dashboard' => 'account/dashboard#index', :as => :dashboard
    match 'home' => 'account/dashboard#index', :as => :home
    resources :skill_requirements, :module => 'account'
  end

  scope '/account', :module => 'account' do
    resources :skill_requests
    resources :profiles
  end

  scope '/vanity', :module => 'vanity' do
     match '/vanity(/:action(/:id(.:format)))', :controller=> 'vanity'
  end

  # NOT LOGGED USER
  match 'home' => 'homes#index', :as => :home
  resources :skill_requirements do
    new do
      get 'skill'
    end
  end

  root :to => 'homes#index'


end

app/views/shared/_ajax_indicator.html.erb
<div id="ajax-indicator" class="hide"><span>Načítám data</span></div>
<% #handling more requests http://stackoverflow.com/questions/6717514/how-to-call-alert-after-all-ajax-requests-are-done  %>
<style type="text/css">
        /* ajax indicator */

    #ajax-indicator {
        position: absolute; /* fixed not supported by IE */
        background-color: #eee;
        border: 1px solid #bbb;
        top: 35%;
        left: 40%;
        width: 20%;
        font-weight: bold;
        text-align: center;
        padding: 0.6em;
        z-index: 20000;
        filter: alpha(opacity = 80);
        opacity: 0.8;
    }

    #ajax-indicator.error {
        background-color: #cc6666;
        border: 1px solid #8b0000;
    }

    #ajax-indicator span {
        background: url('<%= image_path('loading.gif') %>') no-repeat 0% 40%;
        padding-left: 26px;
        vertical-align: bottom;
    }

    html>body #ajax-indicator {
        position: fixed;
    }
</style>
<script type="text/javascript">
    $(document).ajaxStart(function() {
        $('#ajax-indicator').show();
    });
    $(document).ajaxStop(function() {
        if ($('#ajax-indicator').hasClass('error')) {
            $('#ajax-indicator').delay(3000).hide('slow').queue(function(nextt) {
                $(this).removeClass('error');
                $('span', $(this)).text('Nahrávám data');
                nextt();
            })
        } else {
            $('#ajax-indicator').hide();
        }
    });

    $(document).ajaxError(function(e, jqxhr, settings, exception) {
        // abort error is used for iframe upload file
        if (exception != 'abort') {
            $('#ajax-indicator').addClass('error');
            $('#ajax-indicator span').text('Na serveru došlo k chybě :( Error');
        }
    });


</script>

app/views/shared/_facebook.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '304055022939018', // App ID
      channelURL : 'localhost:3000', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      oauth      : true, // enable OAuth 2.0
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     d.getElementsByTagName('head')[0].appendChild(js);
   }(document));
</script>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/cs_CZ/all.js#xfbml=1&appId=304055022939018";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_footer.html.erb
<style type="text/css">
    .footer {
        background: none repeat scroll 0 0 #FFFFFF;
        border-top: 1px solid #E6E6E6;
        background-color: #EDEBE1;
        border-top: 1px solid #cccccc;
    }
        .footer .breadcrumb {
            background: none;
            border: none;
            box-shadow: none;
        }
</style>

<footer class="footer">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="#">Home</a> <span class="divider">/</span></li>
      <li><a href="#">Middle page</a> <span class="divider">/</span></li>
      <li><a href="#">Another one</a> <span class="divider">/</span></li>
      <li class="active">You are here</li>
    </ul>
  </div>
</footer>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26955022-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_header.html.erb
<div class="top-header">
  <%= content_tag :div, :class => 'learning-more' do -%>
      <div class="inner">
        <div class="container">
          <p><span class="icon">?</span> <strong>Co nabízí DůmSnadno.cz?</strong>
            Pomáháme pečovat majitelům nemovitostí o svůj milující domov.
            <a href="3">Zjisti více!</a>
          </p>
        </div>
      </div>
  <% end unless logged_in? -%>
  <div class="topbar-inner">
    <div class="container">
      <%= link_to "DůmSnadno", home_path, :class => 'brand span2' %>
      <ul class="nav span6">
        <%= content_tag :li, :class => ('active' if current_page?(root_url(:anchor => 'skills'))) do -%>
            <%= link_to root_url(:anchor => 'skills') do -%>
                <strong>Podívej se</strong>
                <span>co se tu děje</span>
            <% end %>
        <% end %>
        <%= content_tag :li, :class => ('active' if current_page?(new_skill_requirement_path)
        #current_page?(:controller => 'skill_requirements', :action => 'edit') ||
        #current_page?(:controller => 'skill_requirements', :action => 'show')
        ) do -%>
            <%= link_to(new_skill_requirement_path) do -%>
                <strong>Začni s prací</strong>
                <span>na svém domě</span>
            <% end %>
        <% end %>

        <% if logged_in? %>
            <%= content_tag :li, :class => ('active' if current_page?(profiles_path)) do -%>
                <%= link_to(profiles_path) do -%>
                    <% if current_account.profiles.count == 0 %>
                        <strong>Máte firmu?</strong>
                        <span>vytvořte si profil</span>
                    <% else %>
                        <strong>Pracovní profil</strong>
                        <span>udržba a správa</span>
                    <% end %>
                <% end %>
            <% end %>
        <% else %>
            <%= content_tag :li, :class => ('active' if current_page?(profiles_path)) do -%>
                <%= link_to(profiles_path) do -%>
                    <strong>Máte firmu?</strong>
                    <span>pomozte ostatním</span>
                <% end %>
            <% end %>
        <% end %>

      </ul>

      <ul class="nav sub span4">
        <%= content_tag :li, :class => ('active' if current_page?(login_path)) do -%>
            <span><%= link_to('Poradna', login_path()) %></span>
        <% end %>
        <%= content_tag :li, :class => ('active' if current_page?(new_user_path)) do -%>
            <span>
              <%= link_to('Registrace', new_user_path(:anchor => 'registration-form'), :id => 'register')  %>
            </span>
        <% end  unless current_user %>
        <%= content_tag :li do -%>
            <% if current_user -%>
                <%= link_to(logout_path, :id => 'account') do %>
                    <span>Odhlásit se </span>
                    <strong><%= current_user.email %></strong>
                    <%= image_tag(@me, :height => 28, :alt => '', :style => 'margin-left:2px; float:right; bottom:31px; left:34px;position:relative;') %>

                <% end %>
            <% else %>
                <span><%= link_to('Můj účet', login_path(:anchor => 'new_user_session'), :id => 'account') unless current_user %></span>
            <% end %>

        <% end %>
      </ul>
    </div>
  </div>
</div>