config/routes.rb
# -*- encoding : utf-8 -*-
Dumsnadno::Application.routes.draw do

  # Active Admin
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  
  mount Resque::Server.new, :at => "/resque"

  get "users/index"

  resources :homes
  resources :users do
    member do
      get :activate
    end
  end

  resources :user_sessions

  resources :password_resets

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resource :oauth do
    get :callback
  end
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider


  # LOGGED USER
  scope :constraints => lambda { |req| req.session.include?(:user_id) } do
    match 'dashboard' => 'account/dashboard#index', :as => :dashboard
    match 'home' => 'account/dashboard#index', :as => :home
    resources :skill_requirements, :module => 'account'
  end

  scope '/account', :module => 'account' do
    resources :skill_requests
    resources :profiles
  end

  scope '/vanity', :module => 'vanity' do
     match '/vanity(/:action(/:id(.:format)))', :controller=> 'vanity'
  end

  # NOT LOGGED USER
  match 'home' => 'homes#index', :as => :home
  resources :skill_requirements do
    new do
      get 'skill'
    end
  end

  root :to => 'homes#index'


end

app/controllers/homes_controller.rb
# -*- encoding : utf-8 -*-
class HomesController < ApplicationController
  skip_before_filter :require_login

  def index
  end

  def worker
    Resque.enqueue(Eat, params[:food])
    render :text => 'worker:' + params[:food] + " #{Time.now}"
  end
end

app/helpers/homes_helper.rb
# -*- encoding : utf-8 -*-
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/_header.html.erb
<div class="menu-top">
  <ul>
    <% ['Menu', 'User account', 'Logout'].each do |link| %>
        <li><a href="#"><em class="active"><%= link %></em></a> | </li>
    <% end %>
  </ul>
</div>
<div class="menu1">
  <ul>
    <li>
      <a>
        <em class="active">
          Active menu
        </em>
      </a>
    </li>
    <li>
      <a>
        <em>
          DVD
        </em>
      </a>
    </li>
    <li>
      <a>
        <em>
          New Releases
        </em>
      </a>
    </li>
    <li>
      <a>
        <em>
          Bestsellers
        </em>
      </a>
    </li>
  </ul>
  <div class="white-line"></div>
</div>

app/views/homes/_images_rotation.html.erb
<% content_for :stylesheet_head do -%>
    <!--[if IE]>
    <style type="text/css">
        .timer {
            display: none !important;
        }

        div.caption {
            background: transparent;
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = #99000000, endColorstr = #99000000);
            zoom: 1;
        }
    </style>
    <![endif]-->
<% end %>
<div class="featured-orbit">
  <div class="clip-img">
    <div id="featured">
      <% (1..3).each do |i| %>
          <%= image_tag("featured-#{i}.jpg", 'data-caption' => "#feature#{i}") %>
      <% end %>
    </div>
  </div>
  <span class="orbit-caption" id="feature1">  <span>Truhář: Pavel Vanousek</span></span>
  <span class="orbit-caption" id="feature2">  <span>Truhář: Jindra Ostra</span></span>
</div>

app/views/homes/_login.html.erb
<div id="login-form">
  <form action="#test" data-remote='true'>
    <fieldset>
      <legend>Test me</legend>
      <label for="1">Phone</label>
      <input type="text" value="test me" id="1"/>
      <label for="2">Name</label>
      <input type="text" value="5334 44334 s" id="2"/>

      <button class="button">Submit</button>
    </fieldset>
  </form>
</div>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<% content_for :featured do -%>
    <script type="text/javascript">

/*
            function displayUser(user) {
                var userName = document.getElementById('userName');
                var greetingText = document.createTextNode('Greetings, '
                        + user.name + '.');
                userName.appendChild(greetingText);
            }

            var appID = "304055022939018";
            if (window.location.hash.length == 0) {
                var path = 'https://www.facebook.com/dialog/oauth?';
                var queryParams = ['client_id=' + appID,
                    'redirect_uri=' + window.location,
                    'response_type=token'];
                var query = queryParams.join('&');
                var url = path + query;
                window.open(url);
            } else {
                var accessToken = window.location.hash.substring(1);
                var path = "https://graph.facebook.com/me?";
                var queryParams = [accessToken, 'callback=displayUser'];
                var query = queryParams.join('&');
                var url = path + query;

                // use jsonp to call the graph
                var script = document.createElement('script');
                script.src = url;
                document.body.appendChild(script);
            }
       */
    </script>
    <div id="featured-content">
      <div class="container">
        <div class="row">
          <div class="span6">
            <h1>
              <span class="intro">Hledáte řemeslníky pro svůj domov</span>
              <strong><span>Za nejlepší&nbsp;Cenu</span>
                <span class="icon-ampersand">&amp;</span>&nbsp;<span>Kvalitu</span></strong>
            </h1>

            <p>
              <%= link_to 'Začni právě zde', new_skill_requirement_path,
                          :id => 'start-here',
                          :class => 'btn large primary' %>
            </p>

            <p class="professions"><span class="intro">Zedník, topenář, obkladač, vodař</span>
              <span class="intro">archytekt ... <%= link_to 'a další', '#' %></span>
            </p>
          </div>

          <div class="span6">
            <%= render :partial => 'images_rotation' %>
          </div>
        </div>
      </div>
    </div>

<% end %>

<div class="container">
  <div class="row">&nbsp;<br><br></div>
  <div class="row">
    <div class="page-header">
      <h2>Co zde najdeš?</h2>
    </div>
    <div class="span-one-third">
      <h3>Nezůstaneš v tom sám</h3>
      <ul>
        <li>Komunikace</li>
      </ul>
    </div>
    <div class="span-one-third">
      <h3>Transparentnost
        <small>a cenové srovnání</small>
      </h3>
    </div>
    <div class="span-one-third">
      <h3>Zkušenosti ostatních
        <small>a jejich hodnocení</small>
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="page-header">
      <h2>Právě se stalo</h2>
    </div>
  </div>
</div>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>