config/routes.rb
# -*- encoding : utf-8 -*-
Dumsnadno::Application.routes.draw do

  # Active Admin
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  
  mount Resque::Server.new, :at => "/resque"

  get "users/index"

  resources :homes
  resources :users do
    member do
      get :activate
    end
  end

  resources :user_sessions

  resources :password_resets

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resource :oauth do
    get :callback
  end
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider


  # LOGGED USER
  scope :constraints => lambda { |req| req.session.include?(:user_id) } do
    match 'dashboard' => 'account/dashboard#index', :as => :dashboard
    match 'home' => 'account/dashboard#index', :as => :home
    resources :skill_requirements, :module => 'account'
  end

  scope '/account', :module => 'account' do
    resources :skill_requests
    resources :profiles
  end

  scope '/vanity', :module => 'vanity' do
     match '/vanity(/:action(/:id(.:format)))', :controller=> 'vanity'
  end

  # NOT LOGGED USER
  match 'home' => 'homes#index', :as => :home
  resources :skill_requirements do
    new do
      get 'skill'
    end
  end

  root :to => 'homes#index'


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user_session = User.new
  end

  def create
    respond_to do |format|
      if @user_session = login(params[:user_session][:email], params[:user_session][:password],
                               params[:user_session][:remember])
        format.html { redirect_back_or_to(dashboard_path, :notice => 'Login successfull.') }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
      end
    end
  end

  def destroy
    logout
    redirect_to(login_path(:anchor => 'login-form'), :notice => 'Logged out!')
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_facebook.html.erb
<div class="clearfix">
  <form action="#" class="form-stacked user-form">
    <h3>Facebook</h3>
    <span class="help-block">Vstup na tvůj registrovaný účet</span>
    <%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %>
  </form>
</div>

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= nested_form_for User.new, :as => :user_session, :url => user_sessions_path, :validate => true,
                    :html => {:id => 'new_user_session', :class => 'form-stacked user-form'} do |f| %>
    <div class="clearfix">
      <h3>Můj účet</h3>
      <span class="help-block">Vstup na tvůj registrovaný účet</span>
    </div>

    <div class="clearfix">
      <%= f.label :email %>
      <div class="input">
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :password %>
      <div class="input">
        <%= f.password_field :password %>
      </div>
    </div>

    <div class="clearfix">
      <div class="input">
        <ul class="inputs-list">
          <li>
            <%= label_tag do -%>
                <%= check_box_tag :remember %>
                keep me logged in
            <% end %>
          </li>
        </ul>

      </div>
    </div>

    <div class="actions">
      <%= f.submit :class => 'btn primary', :value => 'Vstup' %>
    </div>

<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/new.html.erb
<div class="row">
  <div class="span-one-third">
    <%= render 'user_sessions/form' %>
  </div>
  <div class="span-one-third">
    <%= render 'users/form' %>
  </div>
  <div class="span-one-third">
    <%= render 'user_sessions/facebook' %>
  </div>
</div>